name: tracker
description: "Aplikasi Ekspedisi Tracker"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  mobile_scanner: ^6.0.7
  barcode: ^2.2.9
  barcode_widget: ^2.0.4
  shared_preferences: ^2.3.5
  intl: ^0.20.2
  printing: ^5.14.1
  pdf: ^3.11.1
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
